	/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cal.h"


float
calcul_1(char *host,float n1,float n2,char opr)
{
	CLIENT *clnt;
	float  *result_1;
	number  add_1_arg;
	float  *result_2;
	number  sub_1_arg;
	float  *result_3;
	number  multi_1_arg;
	float  *result_4;
	number  divi_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCUL, CALVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if (opr=='+')
	{
		add_1_arg.num1=n1;
		add_1_arg.num2=n2;
		add_1_arg.op=opr;
		result_1 = add_1(&add_1_arg, clnt);
		if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	return *result_1;
	}
	else if (opr=='-')
	{
		sub_1_arg.num1=n1;
		sub_1_arg.num2=n2;
		sub_1_arg.op=opr;
		result_2 = sub_1(&sub_1_arg, clnt);
		if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	return *result_2;
	}
	else if (opr=='*')
	{
		multi_1_arg.num1=n1;
		multi_1_arg.num2=n2;
		multi_1_arg.op=opr;

		result_3 = multi_1(&multi_1_arg, clnt);
		if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	return *result_3;
	}
	else if (opr=='/')
	{
		divi_1_arg.num1=n1;
		divi_1_arg.num2=n2;
		divi_1_arg.op=opr;
		result_4 = divi_1(&divi_1_arg, clnt);
		if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	return *result_4;
	}
	
	
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	float n1;
	float n2;
	char ope;

	while(1)
	{
		printf("Enter the numbers and operator:");
		scanf("%f %c %f",&n1,&ope,&n2);
		if (ope=='/' && n2==0)
		{
			printf("You cant divie by 0, try again!\n");
			continue;
		}
		break;
	}
	

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("Answer: %.2f \n",calcul_1 (host,n1,n2,ope));
exit (0);
}
